<?php

namespace AppBundle\Repository;

/**
 * NetworkFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
