<?php

namespace AppBundle\Repository;

/**
 * RemoteSvrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemoteSvrRepository extends \Doctrine\ORM\EntityRepository
{
}
