<?php

namespace AppBundle\Repository;

/**
 * TypeFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
